name = "imagine-test"
compatibility_date = "2025-06-11"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"

main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[r2_buckets]]
binding = 'IMAGINE'
bucket_name = 'imagine'
