name = "imagine"
main = "src/index.ts"
compatibility_date = "2025-06-11"

account_id = "44321e1b7fbd29b56b65c1890a3bbee2"

compatibility_flags = ["nodejs_compat"]
workers_dev = true
browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = 'IMAGINE'
bucket_name = 'imagine'
preview_bucket_name = 'imagine'
